# app = "ime-aplikacije"  # postavlja "fly launch"
primary_region = "fra"

[build]

[env]
  PORT = "3000"

[[mounts]]
  source = "vk_podaci"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
